// Seeds one realistic restaurant on the flexible per-day shift model:
//  - 3 roles; each weekday has manager-defined "בוקר"/"ערב" shifts with
//    staggered role requirements (Sunday matches the exact example the owner gave)
//  - ~20 employees (mixed roles, varied min/max, a few minors, birth dates, wages)
//  - a manager login, a current 'collecting' cycle, and a historical published
//    week (generated by the real engine) so Reports has data immediately

import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { generateSchedule, type ScheduleInput } from '@engine';

const prisma = new PrismaClient();

async function main() {
  await prisma.outboxMessage.deleteMany();
  await prisma.swapRequest.deleteMany();
  await prisma.assignment.deleteMany();
  await prisma.availability.deleteMany();
  await prisma.fairnessLog.deleteMany();
  await prisma.shiftSlot.deleteMany();
  await prisma.shift.deleteMany();
  await prisma.manager.deleteMany();
  await prisma.employeeRole.deleteMany();
  await prisma.weekCycle.deleteMany();
  await prisma.employee.deleteMany();
  await prisma.role.deleteMany();
  await prisma.organization.deleteMany();

  const org = await prisma.organization.create({
    data: {
      name: 'מסעדת הנמל',
      timezone: 'Asia/Jerusalem',
      laborRules: JSON.stringify({ minRestHours: 8, maxWeeklyHours: 45, maxDailyHours: 12, minorCurfewHour: 22, closingHour: 21 }),
    },
  });

  const mkRole = (name: string) => prisma.role.create({ data: { orgId: org.id, name } });
  const waiter = await mkRole('מלצר');
  const cook = await mkRole('טבח');
  const bartender = await mkRole('ברמן');
  const lead = await mkRole('אחראי משמרת');
  const host = await mkRole('מארח/ת');
  const trainee = await mkRole('מתלמד');
  const dish = await mkRole('שוטף כלים');
  const R = { W: waiter.id, C: cook.id, B: bartender.id, L: lead.id, H: host.id, T: trainee.id, D: dish.id };

  // --- per-day shift template ---
  type SlotSpec = { role: string; start: string; count: number };
  type ShiftSpec = { label: string; start: string; end: string; slots: SlotSpec[] };

  const morningWeekday: SlotSpec[] = [
    { role: R.C, start: '06:00', count: 1 },
    { role: R.W, start: '07:00', count: 2 },
    { role: R.W, start: '10:00', count: 1 },
    { role: R.B, start: '11:00', count: 1 },
  ];
  const eveningWeekday: SlotSpec[] = [
    { role: R.L, start: '16:00', count: 1 },
    { role: R.C, start: '16:00', count: 1 },
    { role: R.W, start: '16:45', count: 2 },
    { role: R.W, start: '18:00', count: 1 },
    { role: R.B, start: '18:00', count: 1 },
  ];
  // Sunday = the owner's exact example
  const sundayMorning: SlotSpec[] = [
    { role: R.C, start: '06:00', count: 2 },
    { role: R.W, start: '07:00', count: 3 },
    { role: R.W, start: '10:00', count: 2 },
    { role: R.B, start: '11:00', count: 1 },
  ];
  const sundayEvening: SlotSpec[] = [
    { role: R.L, start: '16:00', count: 1 },
    { role: R.C, start: '16:00', count: 1 },
    { role: R.W, start: '16:45', count: 2 },
    { role: R.W, start: '18:00', count: 2 },
    { role: R.B, start: '18:00', count: 1 },
  ];
  const weekendMorning: SlotSpec[] = [
    { role: R.C, start: '06:00', count: 1 },
    { role: R.W, start: '08:00', count: 3 },
    { role: R.W, start: '10:00', count: 2 },
    { role: R.B, start: '11:00', count: 1 },
  ];
  const weekendEvening: SlotSpec[] = [
    { role: R.L, start: '16:00', count: 1 },
    { role: R.C, start: '16:00', count: 2 },
    { role: R.H, start: '16:45', count: 1 },
    { role: R.W, start: '16:45', count: 3 },
    { role: R.B, start: '16:45', count: 1 },
    { role: R.W, start: '18:00', count: 2 },
    { role: R.B, start: '18:00', count: 2 }, // drives the weekend bartender gaps
  ];

  const daySpec = (day: number): ShiftSpec[] => {
    if (day === 0) return [
      { label: 'בוקר', start: '06:00', end: '16:00', slots: sundayMorning },
      { label: 'ערב', start: '16:00', end: '23:30', slots: sundayEvening },
    ];
    if (day >= 5) return [
      { label: 'בוקר', start: '06:00', end: '16:00', slots: weekendMorning },
      { label: 'ערב', start: '16:00', end: '23:30', slots: weekendEvening },
    ];
    return [
      { label: 'בוקר', start: '06:00', end: '16:00', slots: morningWeekday },
      { label: 'ערב', start: '16:00', end: '23:30', slots: eveningWeekday },
    ];
  };

  const shifts: { id: string; dayIndex: number; label: string; startTime: string; endTime: string; order: number; colorTier: number }[] = [];
  const slots: { id: string; shiftId: string; roleId: string; startTime: string; count: number }[] = [];
  const eveningShiftByDay = new Map<number, string>();

  for (let day = 0; day < 7; day++) {
    const specs = daySpec(day);
    for (let i = 0; i < specs.length; i++) {
      const sp = specs[i]!;
      const shift = await prisma.shift.create({
        data: { orgId: org.id, dayIndex: day, label: sp.label, startTime: sp.start, endTime: sp.end, order: i, colorTier: i },
      });
      shifts.push({ id: shift.id, dayIndex: day, label: sp.label, startTime: sp.start, endTime: sp.end, order: i, colorTier: i });
      if (sp.label === 'ערב') eveningShiftByDay.set(day, shift.id);
      for (const sl of sp.slots) {
        const created = await prisma.shiftSlot.create({ data: { shiftId: shift.id, roleId: sl.role, startTime: sl.start, count: sl.count } });
        slots.push({ id: created.id, shiftId: shift.id, roleId: sl.role, startTime: sl.start, count: sl.count });
      }
    }
  }

  // --- employees ---
  type Seed = { name: string; roles: string[]; min: number; max: number; minor?: boolean; credit?: number };
  const people: Seed[] = [
    { name: 'דנה לוי', roles: [R.W], min: 3, max: 5 },
    { name: 'יוסי כהן', roles: [R.W, R.B, R.L], min: 2, max: 5, credit: 2 },
    { name: 'מאיה בר', roles: [R.W], min: 2, max: 4 },
    { name: 'עידן פרץ', roles: [R.W], min: 3, max: 6 },
    { name: 'נועה שרון', roles: [R.W, R.B], min: 2, max: 4 },
    { name: 'איתי גל', roles: [R.W], min: 1, max: 3, minor: true },
    { name: 'שירה אזולאי', roles: [R.W], min: 1, max: 3, minor: true },
    { name: 'רון מזרחי', roles: [R.W], min: 2, max: 5 },
    { name: 'תמר דוד', roles: [R.W], min: 2, max: 4, credit: 1 },
    { name: 'עומר חדד', roles: [R.W], min: 2, max: 5 },
    { name: 'ליאור נחום', roles: [R.C], min: 3, max: 6 },
    { name: 'גיא אבני', roles: [R.C], min: 3, max: 6, credit: 3 },
    { name: 'סתיו רם', roles: [R.C, R.W, R.L], min: 2, max: 5 },
    { name: 'אורי ביטון', roles: [R.C], min: 2, max: 4 },
    { name: 'הדר שמש', roles: [R.B], min: 2, max: 5 },
    { name: 'ניר עמר', roles: [R.B, R.W], min: 2, max: 5, credit: 1 },
    { name: 'רותם לב', roles: [R.B], min: 2, max: 4 },
    { name: 'אלון פרידמן', roles: [R.W], min: 1, max: 3, minor: true },
    { name: 'יעל שטרן', roles: [R.W], min: 2, max: 4 },
    { name: 'דניאל קפלן', roles: [R.W, R.C, R.L], min: 2, max: 5 },
    { name: 'ליטל אבן', roles: [R.H, R.W], min: 2, max: 4 },
    { name: 'עדן כץ', roles: [R.D], min: 2, max: 5 },
    { name: 'טל רוזן', roles: [R.T, R.W], min: 1, max: 3, minor: true },
    { name: 'שחר גל', roles: [R.L, R.W], min: 2, max: 5, credit: 2 },
  ];

  const rateFor = (roles: string[]) => (roles.includes(R.C) ? 48 : roles.includes(R.B) ? 44 : 38);
  const now = new Date();
  const birthFor = (minor?: boolean) => {
    const age = minor ? 16 + Math.floor(Math.random() * 2) : 22 + Math.floor(Math.random() * 16);
    return new Date(now.getFullYear() - age, Math.floor(Math.random() * 12), 1 + Math.floor(Math.random() * 27));
  };

  const employees = [] as { id: string; name: string; roles: string[]; min: number; max: number; minor: boolean; credit: number }[];
  for (const pp of people) {
    const e = await prisma.employee.create({
      data: {
        orgId: org.id,
        name: pp.name,
        phone: '05' + Math.floor(10000000 + Math.random() * 89999999),
        birthDate: birthFor(pp.minor),
        hourlyRate: rateFor(pp.roles) - (pp.minor ? 6 : 0),
        minShifts: pp.min,
        maxShifts: pp.max,
        isMinor: pp.minor ?? false,
        fairnessCredit: pp.credit ?? 0,
        optInStatus: 'opted_in',
        roles: { create: pp.roles.map((roleId) => ({ roleId })) },
      },
    });
    employees.push({ id: e.id, name: pp.name, roles: pp.roles, min: pp.min, max: pp.max, minor: pp.minor ?? false, credit: pp.credit ?? 0 });
  }

  // --- current cycle (collecting) --- weeks are always anchored to Sunday
  const weekStartOf = (date: Date) => {
    const d = new Date(date);
    d.setUTCHours(0, 0, 0, 0);
    d.setUTCDate(d.getUTCDate() - d.getUTCDay());
    return d;
  };
  const thisSunday = weekStartOf(now);
  const cycle = await prisma.weekCycle.create({ data: { orgId: org.id, weekStartDate: thisSunday, status: 'collecting' } });

  // scattered availability on the current cycle (drives the weekend gaps)
  const byName = (n: string) => employees.find((e) => e.name === n)!;
  const av: { emp: string; shiftId: string; state: 'ok' | 'prefer' | 'cant' }[] = [
    { emp: 'הדר שמש', shiftId: eveningShiftByDay.get(6)!, state: 'cant' },
    { emp: 'רותם לב', shiftId: eveningShiftByDay.get(5)!, state: 'cant' },
    { emp: 'ניר עמר', shiftId: eveningShiftByDay.get(6)!, state: 'cant' },
    { emp: 'עידן פרץ', shiftId: eveningShiftByDay.get(5)!, state: 'prefer' },
    { emp: 'מאיה בר', shiftId: eveningShiftByDay.get(3)!, state: 'prefer' },
  ];
  for (const a of av) {
    await prisma.availability.create({ data: { cycleId: cycle.id, employeeId: byName(a.emp).id, shiftId: a.shiftId, state: a.state } });
  }

  // --- manager login (a dedicated account we "opened" for the branch) ---
  await prisma.manager.create({
    data: { orgId: org.id, name: 'מנהל הסניף', email: 'manager@hanamal.co.il', passwordHash: await bcrypt.hash('demo1234', 10) },
  });

  // platform admin — the ONLY account that can open new businesses (orgId = null)
  await prisma.manager.create({
    data: { name: 'מנהל-על', email: 'admin@sadran.co.il', passwordHash: await bcrypt.hash('admin1234', 10), isAdmin: true },
  });

  // --- historical published week (via the real engine) so Reports has data ---
  const input: ScheduleInput = {
    weekendDays: [5, 6],
    laborRules: { minRestHours: 8, maxWeeklyHours: 45, maxDailyHours: 12, minorCurfewHour: 22, closingHour: 21 },
    shifts: shifts.map((s) => ({ id: s.id, dayIndex: s.dayIndex, label: s.label, startTime: s.startTime, endTime: s.endTime, order: s.order, colorTier: s.colorTier })),
    demand: slots.map((s) => ({ id: s.id, shiftId: s.shiftId, roleId: s.roleId, startTime: s.startTime, count: s.count })),
    employees: employees.map((e) => ({ id: e.id, name: e.name, roleIds: e.roles, minShifts: e.min, maxShifts: e.max, isMinor: e.minor, fairnessCredit: e.credit })),
    availability: [],
  };
  const result = generateSchedule(input);

  // three published weeks of history (an archive to browse)
  let latestHistId = '';
  for (let w = 1; w <= 3; w++) {
    const d = new Date(thisSunday);
    d.setUTCDate(d.getUTCDate() - 7 * w);
    const hist = await prisma.weekCycle.create({ data: { orgId: org.id, weekStartDate: d, status: 'published' } });
    if (w === 1) latestHistId = hist.id;
    await prisma.assignment.createMany({
      data: result.assignments.map((a) => ({ cycleId: hist.id, employeeId: a.employeeId, shiftId: a.shiftId, slotId: a.slotId, roleId: a.roleId, startTime: a.startTime, status: 'published' })),
    });
    await prisma.fairnessLog.createMany({
      data: result.fairness.map((f) => ({ cycleId: hist.id, employeeId: f.employeeId, undesirableLoad: f.undesirableLoad, count: f.count })),
    });
  }

  const someAssignments = await prisma.assignment.findMany({ where: { cycleId: latestHistId }, take: 30 });
  const picks = [someAssignments[3], someAssignments[12], someAssignments[21]];
  for (const a of picks) {
    if (!a) continue;
    const cover = employees.find((e) => e.id !== a.employeeId)!;
    await prisma.swapRequest.create({
      data: { cycleId: latestHistId, assignmentId: a.id, status: 'approved', previousHolderId: a.employeeId, claimedById: cover.id },
    });
  }

  console.log(
    `Seeded org "${org.name}" · ${employees.length} employees · ${shifts.length} shifts · 7 roles · login manager@hanamal.co.il / demo1234\n` +
      `Archive: 3 published weeks (${result.assignments.length} shifts each), ${picks.filter(Boolean).length} swaps`,
  );
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
